//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FontValidatorService.Glyph {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NS_Glyph_GErrStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NS_Glyph_GErrStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FontValidatorService.Glyph.NS_Glyph.GErrStrings", typeof(NS_Glyph_GErrStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A1110: Application error.
        /// </summary>
        internal static string GERR_APPLICATION {
            get {
                return ResourceManager.GetString("GERR_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E1112: Bounding box is incorrect.
        /// </summary>
        internal static string GERR_BBOX {
            get {
                return ResourceManager.GetString("GERR_BBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E1118: Circular dependency of composite glyph&apos;s components.
        /// </summary>
        internal static string GERR_COMPONENT_CIRCULAR_DEPENDENCY {
            get {
                return ResourceManager.GetString("GERR_COMPONENT_CIRCULAR_DEPENDENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E1121: Duplicated components of composite glyph.
        /// </summary>
        internal static string GERR_COMPONENT_DUPL {
            get {
                return ResourceManager.GetString("GERR_COMPONENT_DUPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E1123: An empty component of the composite glyph.
        /// </summary>
        internal static string GERR_COMPONENT_EMPTY {
            get {
                return ResourceManager.GetString("GERR_COMPONENT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E1117: Shift of component either undefined or ambigously defined.
        /// </summary>
        internal static string GERR_COMPONENT_INCORRECT_SHIFT {
            get {
                return ResourceManager.GetString("GERR_COMPONENT_INCORRECT_SHIFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E1116: Component transform matrix is degenerated.
        /// </summary>
        internal static string GERR_COMPONENT_INCORRECT_TRANSFORM {
            get {
                return ResourceManager.GetString("GERR_COMPONENT_INCORRECT_TRANSFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E1113: Invalid glyph index of component.
        /// </summary>
        internal static string GERR_COMPONENT_INDEX_GLYPH {
            get {
                return ResourceManager.GetString("GERR_COMPONENT_INDEX_GLYPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E1114: Invalid index of knot in composite glyph.
        /// </summary>
        internal static string GERR_COMPONENT_INDEX_KNOT {
            get {
                return ResourceManager.GetString("GERR_COMPONENT_INDEX_KNOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W1110: Intersecting components of composite glyph.
        /// </summary>
        internal static string GERR_COMPONENT_INTERS {
            get {
                return ResourceManager.GetString("GERR_COMPONENT_INTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E1115: Failure to load the component.
        /// </summary>
        internal static string GERR_COMPONENT_LOAD_FAILURE {
            get {
                return ResourceManager.GetString("GERR_COMPONENT_LOAD_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W1113: Degenerated contour(s).
        /// </summary>
        internal static string GERR_CONT_DEGEN {
            get {
                return ResourceManager.GetString("GERR_CONT_DEGEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E1120: Duplicated contours.
        /// </summary>
        internal static string GERR_CONT_DUPL {
            get {
                return ResourceManager.GetString("GERR_CONT_DUPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E1111: Intersecting contours.
        /// </summary>
        internal static string GERR_CONT_INTERS {
            get {
                return ResourceManager.GetString("GERR_CONT_INTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E1110: Misoriented contour.
        /// </summary>
        internal static string GERR_CONT_MISOR {
            get {
                return ResourceManager.GetString("GERR_CONT_MISOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E1119: Wrapped contour(s) .
        /// </summary>
        internal static string GERR_CONT_WRAP {
            get {
                return ResourceManager.GetString("GERR_CONT_WRAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W1112: Not all extremes are marked with the on-curve control points .
        /// </summary>
        internal static string GERR_EXTEREME_NOT_ON_CURVE {
            get {
                return ResourceManager.GetString("GERR_EXTEREME_NOT_ON_CURVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W1111: Duplicated knots.
        /// </summary>
        internal static string GERR_KNOT_DUPL {
            get {
                return ResourceManager.GetString("GERR_KNOT_DUPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A1112: Test aborted.
        /// </summary>
        internal static string GERR_VAL_ABORTED {
            get {
                return ResourceManager.GetString("GERR_VAL_ABORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A1113: Test failed because of unhandeled exception.
        /// </summary>
        internal static string GERR_VAL_FAILURE {
            get {
                return ResourceManager.GetString("GERR_VAL_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A1111: Unable to perform test due to previously detected errors.
        /// </summary>
        internal static string GERR_VAL_UNABLE_TO_PERFORM_TEST {
            get {
                return ResourceManager.GetString("GERR_VAL_UNABLE_TO_PERFORM_TEST", resourceCulture);
            }
        }
    }
}
